### ISSUE TITLE
(Another) floating point parsing issue with a non-English locale

### ISSUE THREAD

**Issue by paavohuhtala** [OpenSAGE/OpenSAGE#10]
In `IniParser.cs`, `ScanFloat` uses `Convert.ToSingle` without specifying `InvariantCulture`. This can be fixed by using `ParseUtility.ParseFloat()` instead.

Issues like this are likely to appear again, since they are easy to make and hard to spot. They could be prevented with a couple different ways:
* Run the test suite with a few different thread cultures, either a fixed set or even a random selection.
  * Not sure if there's an established way of doing this with Xunit.
  * If it's done with the entire test suite, it would essentially at least double the execution time.
  * Only catches the code covered with tests.
  * From what I've gathered, the test suite is not currently being run in CI, so this would rely on contributors running the tests manually after each and every change.
* Write a Roslyn analyzer which forbids (and possibly quick-fixes) the use of `float.Parse`, `Convert.ToSingle` and other functions which require a culture parameter to work portably.
  * Unless one exists already, requires a bit more engineering.
  * Only catches a specific set of issues, although they are the most likely ones to occur.

I could look into contributing either solution later in December, if you think it'd be useful.

**Comment by tgjones** [comment]
Oops, I just realised I didn't reply to this. Thank you for the PR, which I've just merged :)

I am in the process of setting up CI, which will run all the tests. I will look into running at least the `.ini` parsing tests multiple times for different locales.
