### ISSUE TITLE
Implement proper game loop

### ISSUE THREAD

**Issue by paavohuhtala** [OpenSAGE/OpenSAGE#102]
At the time of writing the game loop is very simple: `Game.Tick()` is called as often as possible. `Game.Tick()` polls for input, processes incoming messages from the network message buffer, updates game systems and renders the frame. This has been fine for now, but it doesn't match how SAGE works.

As far as I know, SAGE works kinda like this:

* The scripting system [updates at 30 FPS](https://opensage.readthedocs.io/systems/scripting/index.html).
* Other game systems also update at 30 FPS.
* The game normally renders at ~30 FPS (GeForce Experience reports the framerate in the shell map as 32 fps)
* Network messages and (possibly) player input are processed at 15 FPS
  * Could we poll input more often to reduce input lag without breaking compatibility?

If I had to guess I'd say the original implementation runs a single game loop at 30 FPS, updates network messages and input every other frame and then does everything else, including rendering.

There are some special cases, some of which we need to support and some which we might want to support:

* When the pause menu is open, all units freeze, particles stop animating and vertex animations (tree sway) stop. At least in Generals, animated textures (rivers) continue animating, although this could be more of an oversight rather than a decision. The UI system operates normally.
* The "freeze time" scripting action works very similarly to the pause menu. The script which starts the pause should probably continue executing, so that the game doesn't get stuck. This requires further research.
* In single player skirmish Generals has a game speed slider, which goes from 15 to 60 + unlimited (shown as two minus signs) and defaults to 30. This affects both gameplay systems and rendering. At unlimited the game runs as fast as it can (on my computer about 700 FPS in a small 1v1 map).
  * On my computer with game speed set to 60 the game renders at 67 FPS, which is probably unintentional.

Personally I would love to see rendering supported at arbitrary framerates. This is probably the biggest enhancement we can do to for the original games, since AFAIK every single SAGE game is locked to 30 FPS. In the age of powerful enough hardware and enthusiasts having 120-240hz screens, it doesn't make sense to stick to 30.

**Comment by Continous** [comment]
It would be nice to make the "gamespeed" slider effect tickrate, but not speed, and maybe make that toggleable. Maybe also allowing the gamespeed slider to be expanded. And an adjustable default gamespeed.

**Comment by Continous** [comment]
Correct. Ideally, the game renders at whatever rate the computer will allow, perhaps with a v-sync option.

UI should be rendered at the same rate as the game render.

All logic should be tied to a master clock independent of framerate, and all other timings should be derived from this.

This avoids any problems such as gamespeed being tied to framerate, high framerates causing issues with gamespeed or physics, and most importantly, allows increasing the gamespeed without significantly increasing the demand on the system.
