### ISSUE TITLE
Render shadows

### ISSUE THREAD

**Issue by paavohuhtala** [OpenSAGE/OpenSAGE#103]
Shadows are very important for the visual look of Generals.

Generals implemented them using shadow volumes, but we might implement them using shadow maps instead. TBD.

**Comment by tgjones** [comment]
From what I can gather:
* Generals and Zero Hour used shadow volumes
* All subsequent SAGE games used shadow maps - specifically a single shadow map, with size based on quality settings

For comparison, StarCraft II appears also to use a single shadow map, with size based on quality settings.

I'd like to try out cascaded shadow maps. A few years ago I [did a MonoGame implementation](http://timjones.io/blog/archive/2015/04/13/cascaded-shadow-maps-sample-for-monogame) that had good results, including visual niceties like normal offset, blending across cascades, and variable PCF filter size.

An argument *against* cascaded shadow maps would be that the top-down view typical in RTS games means a single shadow map would be good enough, in most cases. That may well be the case, but I think even for the typical top-down view, cascaded shadow maps will still improve shadow quality. And there should be a noticeable different for cinematic camera angles.

If we do implement cascaded shadow maps, there'd be nothing stopping us having a "low" quality setting where there's only one cascade, i.e. fallback to simple shadow maps.

**Comment by Continous** [comment]
Any chance we will get modern shadowmapping futures? Such as contact-hardening shadows?

**Comment by feliwir** [comment]
Isn't this fixed by now?

**Comment by tgjones** [comment]
Not really - I was planning to close it when shadows are enabled by default. Which will be after I've fixed a few more bugs.

**Comment by Continous** [comment]
Did we decide on cascade shadow maps? If so, will Generals/Zero Hero have the simple shadow map as default or...

**Comment by feliwir** [comment]
We currently use cascaded shadow maps with up to 4 cascades. The resolution & the amount of shadowmaps can be customized through our developer mode (F11). Still some work remains though

**Comment by feliwir** [comment]
Was fixed by #544
