### ISSUE TITLE
Construct a cell passability map and implement path finding

### ISSUE THREAD

**Issue by paavohuhtala** [OpenSAGE/OpenSAGE#105]
Likely depends on #104.

We need to construct a navmesh from the passability data stored in the map file, create paths for bridges and carve out areas where there are buildings and other map objects. The navmesh should be efficient to update with newly constructed and destroyed buildings. We then need to implement a pathfinding algorithm (probably A*) to query the navmesh.

I did a highly scientific experiment which suggests that units are not included in the nav mesh:

![image](https://user-images.githubusercontent.com/803180/38778943-c167935e-40c9-11e8-87bc-dc5098fb9d40.png)

The tanks are in an another team than the officer in the middle, so they don't move to let him through. When I order the officer to move out of the square of tanks, he'll start moving but gives up when he reaches the point nearest to his goal.

![image](https://user-images.githubusercontent.com/803180/38778970-3dda58fe-40ca-11e8-9063-82b878f7721d.png)

If I try to move to a completely unreachable place (like this conveniently placed group of barracks) instead, the cursor turns to 🚫 when I hover over it, and the unit moves to the closest point it can.

(The cursor is different because my screenshot key combination includes CTRL)

Unit movement "plans" can be seen by holding down ALT. The same key is also used to give multiple move orders in a row. Using that + good old spam clicking resulted in the following image:

![image](https://user-images.githubusercontent.com/803180/38779249-755a7864-40ce-11e8-93c6-b7a1cb03ee90.png)

All unit positions are aligned to a grid, perhaps with a resolution of 1 game unit. This might or might not tell something about the navmesh.

**Comment by Qibbi** [comment]
SAGE works with cells, not a navmesh.

**Comment by paavohuhtala** [comment]
Some parts of this are present in #140.

**Comment by feliwir** [comment]
Are we done with this @paavohuhtala ?
