### ISSUE TITLE
The menu doesn't appear after exiting the credits 

### ISSUE THREAD

**Issue by TiberiumRaider** [OpenSAGE/OpenSAGE#144]
I can exit the credits, however, I can't go back to the main menu since it doesn't appear and the application itself crashes.

**Comment by feliwir** [comment]
@TiberiumRaider on what platform are you? It works perfectly fine for me with release 0.3.0. No crashes or anything.

**Comment by TiberiumRaider** [comment]
Never mind, it seems like an error on my end.
