### ISSUE TITLE
Viewer currently only searches for system variables on detecting installations

### ISSUE THREAD

**Issue by Tarcontar** [OpenSAGE/OpenSAGE#174]
At the moment the viewer and specifically the method to locate game installations only searches in the system environment variables for installation paths, would be neat if it could also search in the user environment variables.
This could be done by setting the following parameter in the function:

String path = Environment.GetEnvironmentVariable("BFME_PATH", EnvironmentVariableTarget.User);

In InstallationLocator.cs.

**Comment by tgjones** [comment]
Fixed by #175.
