### ISSUE TITLE
Tga loading issues when use of alpha channel

### ISSUE THREAD

**Issue by feliwir** [OpenSAGE/OpenSAGE#18]
When viewing .tga files that make use of transparency i am getting artifacts at the edges;
![image](https://user-images.githubusercontent.com/2104576/34416171-902a0e74-ebf2-11e7-99fa-b519f44b5e25.png)

In FinalBig the image is displayed correctly:
![image](https://user-images.githubusercontent.com/2104576/34416198-a9b6b6bc-ebf2-11e7-810a-4fbc7f253777.png)

**Comment by feliwir** [comment]
This seems to be a bug inside the SaveAsBmp method, provided by ImageSharp. I've reported the bug and wait for a response

**Comment by tgjones** [comment]
Fixed by #20.
