### ISSUE TITLE
Integrate a logging solution

### ISSUE THREAD

**Issue by paavohuhtala** [OpenSAGE/OpenSAGE#218]
There are bunch of places inside the engine where we'd want to log errors and warnings about potentially invalid map / asset data. Many of these places have been marked with TODO labels.

This should also help with debugging issues when we have some users that are not just developers.

We don't need a fancy logging solution, but there are potential benefits to having a system that includes things like subsystem labels, log levels (verbose/info/warning/error) and logging to multiple targets, such as files, stdout and an internal buffer.

[NLog](https://github.com/NLog/NLog) is apparently decent - full featured, but hopefully not too heavy - so I guess we'll try it unless something immensely better appears.

**Comment by feliwir** [comment]
This has been done
