### ISSUE TITLE
Handle MapObjects being placed outside heightmap boundaries

### ISSUE THREAD

**Issue by paavohuhtala** [OpenSAGE/OpenSAGE#22]
`LoadObjects` in `MapLoader.cs` should do a bounds check before calling `GetHeight`. If the object is outside of height map boundaries, it should use a different height.

I don't know what that height should be. I encountered this in `CHI07.map`, where two jets were placed outside boundaries so that they can fly in in a cinematic. Maybe `PreferredHeight` for things that have a locomotor, and 0 for others?

**Comment by tgjones** [comment]
> Maybe `PreferredHeight` for things that have a locomotor, and 0 for others?

That sounds sensible. Since we haven't hooked up locomotors yet, we could set it to 0 for now, with a TODO to use the Locomotor `PreferredHeight` once that code is written?
