### ISSUE TITLE
BigArchiveTests.ReadFirstEntryStream doesn't (and cannot ever?) pass

### ISSUE THREAD

**Issue by paavohuhtala** [OpenSAGE/OpenSAGE#25]
This is what the test looks like:

```csharp
[GameFact(SageGame.CncGeneralsZeroHour)]
public void ReadFirstEntryStream()
{
    using (var bigStream = File.OpenRead(_bigFilePath))
    using (var bigArchive = new BigArchive(bigStream))
    {
        var firstEntry = bigArchive.Entries[0];

        using (var firstEntryStream = firstEntry.Open())
        {
            Assert.Equal(9334, firstEntryStream.Length);

            var buffer = new byte[firstEntryStream.Length];
            var readBytes = firstEntryStream.Read(buffer, 0, 10000);
            Assert.Equal(9334, readBytes);
        }
    }
}
```
It throws an `ArgumentException` on the line containing `firstEntryStream.Read`, because it's trying to read (up to) 10000 bytes into a buffer with the length of 9334. This matches the [documented behavior](https://docs.microsoft.com/en-us/dotnet/api/system.io.memorystream.read?view=netframework-4.7.1).

I dont't think this could ever pass. 😄

**Comment by tgjones** [comment]
Thanks! Fixed. Some of these tests have indeed never passed. I've been working on tests this week (the map roundtrip tests now pass), but I hadn't got to this one yet.
