### ISSUE TITLE
Maps only render one instance of each mesh

### ISSUE THREAD

**Issue by paavohuhtala** [OpenSAGE/OpenSAGE#26]
e.g in Lone Eagle, you can only see one supply depot, one sewage pipe, one copy of each tree and building and so on.

Will investigate later.

**Comment by paavohuhtala** [comment]
This regression was introduced in 61994bee78f963a40eb4fea2c86c8113ceef78ab .

**Comment by paavohuhtala** [comment]
If I'm interpreting the graphics debugger correctly, all instances do get rendered, but at the same coordinates.

![image](https://user-images.githubusercontent.com/803180/34496477-6e2395fc-f002-11e7-9844-5dd07b2aa120.png)

`VSSetConstantBuffers` seems to only get called once per unique mesh, and is then reused for subsequent draw calls. That buffer presumably contains the world matrix.

**Comment by paavohuhtala** [comment]
[This line](https://github.com/OpenSAGE/OpenSAGE/blob/7c760c195ccf5859c4e474271afdcd44c39674f3/src/OpenSage.Game/Graphics/Rendering/RenderPipeline.cs#L100) could be the culprit. It updates the `RenderItemConstantsVS` buffer for each render item, but that buffer is only used by `Terrain.fx` and `Particle.fx`. Most meshes use the `MeshConstants` cbuffer, which is only updated in the ModelMesh constructor (?).

**Comment by paavohuhtala** [comment]
@tgjones could you have a look at this when you have the time? I don't understand the renderer well enough to fix this. See the comments above for some observations.

**Comment by tgjones** [comment]
Will do. Thanks for diagnosing the issue, that will help.
