### ISSUE TITLE
Breakout W3D to separate project

### ISSUE THREAD

**Issue by jpf200124** [OpenSAGE/OpenSAGE#260]
Hey guys,

Not an issue per se...but:

@tgjones talked about this in my previous PR. I was just wondering when we might expect the w3d parsing to be pulled out into a separate project? 

I am developing a w3d to gltf converter and would like to reference a nuget package perhaps?

Thanks!

**Comment by tgjones** [comment]
I'm planning to do that very soon. There are a couple of in-flight PRs that touch code that will need to be moved, so I'm waiting for those to be merged first.
