### ISSUE TITLE
AI Challenges

### ISSUE THREAD

**Issue by mghayour** [OpenSAGE/OpenSAGE#267]
Hello
I am Mahdi Ghayour from iran, and i study computer engineering in Ferdowsi university of Mashhad.
This is a greate job, i love generals too and i am really happy that i find this repository

I want to add some features to this game that able programmers to make their own Ai with any programming language.
After this feature we can have some cool programming challenges and i think it would be perfect.

how we can help you ? to do this?

**Comment by feliwir** [comment]
Hey, this is currently out of scope for us, so i'll close this issue for now

**Comment by fengmao31** [comment]
I learn some about Reinforcement learning and starcraft ai. I think it is probably to do it. if the OpenSAGE is finished, I can work on this. only need some APIs to give the environment and read the file about the command from another program.
I like zero-hours and I want to design a ai for it to win humans.
