### ISSUE TITLE
Implement LUA

### ISSUE THREAD

**Issue by MetaIdea** [OpenSAGE/OpenSAGE#283]
I recommend using these ressources for implementing LUA in OpenSage:

https://www.lua.org/ftp/lua-4.0.1.tar.gz
OR https://www.lua.org/ftp/lua-5.3.5.tar.gz

http://nlua.org/

https://github.com/nrother/dynamiclua

Adding the most recent LUA 5.3.5 instead of the old 4.01 used in SAGE (BFME2 and upwards) would also be viable. There are few functions (mainly IO, math, string and table functions) that need to be redirected then. For example 
5.3: "string.sub" -> 4.01: "strsub" 
5.3: "io.open" -> 4.01: "open" 
5.3: "table.insert" -> 4.01: "tinsert" 
5.3: "math.random" -> 4.01: "random" 

There's also the globals table accessible with globals()[index] in lua that holds all global functions, variables and also a reference to each lua registered game object that have indexes like these: "ObjID#00000001" or "ObjID#0000004a". These object references have the lua data type "table".

The scripts.lua from the game files gets loaded on each new map start. Note each object that got lua code in their animation data section has it's own lua space seperated from other objects lua space as well as from the main script.lua variable space.

The globals() table with all global variables, functions and so on should ideally be a part of the savegame as well.

Having lua even in C&C Generals would be a nice optionality too.

**Comment by feliwir** [comment]
Hey, 
thanks for that issue we definetly are aware that we are missing a LUA interpreter as of now. 
Do you know if the latest Lua is fully backwards compatible to LUA 4.01? Also i think it might be interesting for us to use luajit for performance. We should definetly collect what's necessary in this issue here.

**Comment by MetaIdea** [comment]
Thanks for your quick reply. LUA 5.3.5 has slightly different ways to call certain functions as stated above. From a function input and output perspective all commonly used functions behave equal to LUA 4.0.1 afaik. Since original SAGE LUA has quite some additions and slight deviations anyway, it shouldn't make a huge difference to use a more recent lua and do the few adjustments. This is a good ressource from tomsons26: https://github.com/tomsons26/Westwood-Info-Repo/blob/master/SAGE_LUA.md
Note that later games have some more events and functions.

**Comment by feliwir** [comment]
@MetaIdea i think since we have an initial version by you, this issue can be closed? The additional LUA features should be seperate issues.
