### ISSUE TITLE
Multiplayer map "Woodcrest Circle" doesn't load

### ISSUE THREAD

**Issue by paavohuhtala** [OpenSAGE/OpenSAGE#32]
Also known as the only map ever to use DEFLATE compression.

Crashes on load, because `MapFile.ParseMapData` contains the following line:
```csharp
context.PushAsset(nameof(MapFile), reader.BaseStream.Length);
```

.. and `DeflateStream` [doesn't support](https://msdn.microsoft.com/en-us/library/system.io.compression.deflatestream.length(v=vs.110).aspx) the `Length` property.

**Comment by OmniBlade** [comment]
It should be noted that this map isn't actually a complete map, its not available to play by default in the original game and is actually an earlier build of another map. As such not being able to load it isn't the end of the world.
