### ISSUE TITLE
Generals: skirmish screen doesn't allow map location selection

### ISSUE THREAD

**Issue by DaanMeijer** [OpenSAGE/OpenSAGE#321]
When I start a skirmish game, I can't select my starting position on the map. I can click the map locations, but I can't choose where to start. Also needs feedback in the form of a player number on the selected location.

**Comment by feliwir** [comment]
Yep, i didn’t implement those yet. Thanks for the reminder.It’s in the GuiCallbacks (part of mods) when you are interested in this yourself.
