### ISSUE TITLE
Cross platform

### ISSUE THREAD

**Issue by TheChosenEvilOne** [OpenSAGE/OpenSAGE#33]
I think a this project should go linux also 
it seems like a switch to OpenGL should be mostly enough

**Comment by feliwir** [comment]
@TheChosenEvilOne 
The big advantage that Direct3D/2D offers at the moment is that it's easy to draw text using DirectWrite. For the OpenGL backend we need atleast a seperate Font rasterizer (probably Freetype, as it is the defacto standard on most Linux systems) and another libary to handle access to system fonts and do Font caching (Fontconfig would be the route here i think).

**Comment by amerkoleci** [comment]
Why not using Veldrid (https://github.com/mellinoe/veldrid)? It has WIP support also for Metal.
I'm also working also on .NET game engine with .NET Standard support (https://github.com/amerkoleci/alimer)

**Comment by tgjones** [comment]
@amerkoleci because I think it’s important that we own the platform abstraction layer, and I have experience at building this stuff.

**Comment by amerkoleci** [comment]
@tgjones sure you have, just was proposing to take look tho :)
