### ISSUE TITLE
Fire in BfME2

### ISSUE THREAD

**Issue by MinecraftPlaye** [OpenSAGE/OpenSAGE#409]
I've found some interesting GDC talk about BFME2 and fire in the Sage Engine:
https://www.gdcvault.com/play/1013291/Middle-earth-is-Burning-Fire

Maybe this piece of information becauses useful at some point. ;)

**Comment by tgjones** [comment]
This was a great listen, thank you! There were some really interesting details about SAGE and BFME2 in that talk.

I'm going to close this issue because it will still be here when we search for it 😄
