### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by paavohuhtala** [OpenSAGE/OpenSAGE#41]
At the time of writing, OpenSAGE only runs on Windows. There's also some code for macOS support.

In order to support Linux we need to do at least the following things:

* Handle window creation
   * With fullscreen support
* Handle mouse and keyboard input
* Implement an OpenGL or Vulkan renderer
    * Preferably OpenGL, since it also runs on macOS and on older GPUs.
* Make sure OpenSAGE builds and runs on Mono or CoreCLR
* Implement an `IInstallationLocator` that doesn't use the Windows registry
    * This could be done with a config file or a command line argument.
* Embed the game view into `Eto.Forms` for the data viewer
* Make sure OpenSAGE works on a case-sensitive file system

These will also benefit the macOS port.

Feel free to comment with your ideas, recommendations and war stories.

**Comment by tgjones** [comment]
We have a [plan](https://github.com/OpenSAGE/OpenSAGE/projects/1) for this now. I'll leave this issue open until that work is complete.

I've mainly thought about making it *possible* for OpenSAGE to be cross-platform. Some of the items above (such as implementing an `IInstallationLocator` that doesn't use the Windows registry) can be done (very soon) after that.

**Comment by feliwir** [comment]
We should probably add a note that Arial.ttf is not installed by default. On Ubuntu i needed the following commands:
```bash
sudo apt-get install ttf-mscorefonts-installer
sudo fc-cache
```

**Comment by feliwir** [comment]
![screenshot from 2018-05-10 21-09-53](https://user-images.githubusercontent.com/2104576/39889131-3fea547e-5497-11e8-81fd-5dca6f747acc.png)
I think this issue can be closed. The visual issues are not due to linux, but related to OpenGL (and also happen on Windows)
