### ISSUE TITLE
BFME1 W3D issues

### ISSUE THREAD

**Issue by tomsons26** [OpenSAGE/OpenSAGE#42]
gbmtgametest.w3d and orcpile.w3d crashes at
modelloader.cs
if (w3dHierarchy.Pivots.Length > ModelMesh.MaxBones) {
throw new NotSupportedException();
}

sauroneyecine.w3d crashes in private static FixedFunctionMaterial.TextureMappingType ToTextureMappingType(this W3dVertexMappingType value), value was StepLinearOffset

This is probably going to be updated is i poke around the files more.

**Comment by feliwir** [comment]
Fixed with #198
