### ISSUE TITLE
Remove Metal rendering backend

### ISSUE THREAD

**Issue by tgjones** [OpenSAGE/OpenSAGE#45]
Farewell Metal, we barely knew you...

**Comment by Phrohdoh** [comment]
Why remove a (presumably) working Metal backend just because an OpenGL backend is planned?

Less overall code to support?

**Comment by feliwir** [comment]
@Phrohdoh we currently are evaluating [Veldrid](https://github.com/mellinoe/veldrid), which does also include a Metal backend. But yes, the idea is to only maintain a single backend (which Veldrid would still allow us).

**Comment by tgjones** [comment]
What @feliwir said, plus it was only partially implemented. I hadn’t written (or cross-compiled) the shaders in Metal SL.
