### ISSUE TITLE
Getting results from replay files

### ISSUE THREAD

**Issue by inktrap** [OpenSAGE/OpenSAGE#703]
Sorry if this is not the right place to ask this … I wondered how I could get the results (who played, who won, how? (disconnect/regularly/…)) from a replay file … I already can get timecodes and player info [through this reader](https://github.com/louisdx/cnc-replayreaders/blob/master/ccgzhreader.cpp) and some workings are [described here](http://timjones.io/blog/archive/2018/03/06/parsing-command-and-conquer-generals-replay-files). But the account is inactive and since you implemented replay parsing through opensage I guessed that I'll just ask someone/some people who know.

**Comment by lanyizi** [comment]
IIRC replay does not store result by itself, it just store player's commands, and when the game plays the replay file, it's really playing the match again, so you cannot know the outcome until the entire simulation ends.

**Comment by inktrap** [comment]
So the only way to get to a result would be to run the replay file and then to take screenshots (or a recording that could be split into frames) towards the end with the goal to capture the result screen and to do ocr over that?

If this works somehow, there are additional problems to run this headless. One could use a virtual machine and take screenshots, but loading replays has to happen via gui so perhaps this could work if there is only one replay available and it is renamed to something recognizeable, like `▉▉▉▉▉▉▉▉.rep`, and for menu navigation everything has to be deactivated (background movie, intro movie, …) https://www.gamereplays.org/community/index.php?showtopic=234

Can OpenSAGE run replays via CLI and display the result screen?

So I'll do something like: `OpenSAGE.exe --replay my-replay.rep`

**Comment by OmniBlade** [comment]
Won't matter how you can run OpenSAGE since it doesn't have a full implementation of the simlulation yet so any attempt to replay a replay using it will diverge from what actually happened. Worse news is that it will likely never deterministically match the original simulation to the degree needed to faithfully replay a replay file from the original game even if it ends up using the same replay format.

**Comment by inktrap** [comment]
Okay, so it would be original generals if it works at all … thanks for your answers and insights
