### ISSUE TITLE
Generals: subobjects are not hidden from drawables

### ISSUE THREAD

**Issue by charliefoxtwo** [OpenSAGE/OpenSAGE#844]
![image](https://github.com/OpenSAGE/OpenSAGE/assets/30303272/3711d1e9-ed98-499f-be6a-dbeeee802dff)
From left to right:
- marauder tank has 3 multiple barrels, which it only gets with scrap upgrades
- quad cannon also has scrap-upgraded weapon
- radar van has radar mast on the back, which is granted with the Radar Van Scan science researched at the Black Market

It's also quite visible on the shellmap, where humvees have the tow missile upgrade component shown
![image](https://github.com/OpenSAGE/OpenSAGE/assets/30303272/564634e0-5a47-4a1f-8558-edec7bdc5f7d)

Note in the ini for the humvee that `TurretUp01` is hidden by default, and only shown when the player has the requisite upgrade.
```ini
ConditionState = NONE
  Model = AVHUMMER
  Turret = Turret
  ShowSubObject = Turret
  HideSubObject = TurretUp01 Housecolor03 MuzzleFXUP01
  WeaponFireFXBone = PRIMARY Muzzle
  WeaponMuzzleFlash = PRIMARY MuzzleFX
End

; ...

ConditionState = WEAPONSET_PLAYER_UPGRADE
  Model = AVHUMMER
  Turret = TurretUp01
  HideSubObject = Turret MuzzleFX01
  ShowSubObject = TurretUp01 Housecolor03
  WeaponFireFXBone = PRIMARY MuzzleUp
  WeaponMuzzleFlash = PRIMARY MuzzleFXUp
  WeaponFireFXBone = SECONDARY WeaponB
  WeaponLaunchBone = SECONDARY WeaponB
  WeaponFireFXBone = TERTIARY WeaponB
  WeaponLaunchBone = TERTIARY WeaponB
End
```

**Comment by c001ac1d** [comment]
we have 2 problems regarding this.

### first
```ini
ConditionState = NONE
  Model = AVHUMMER
  Turret = Turret
  ShowSubObject = Turret
  HideSubObject = TurretUp01 Housecolor03 MuzzleFXUP01
  WeaponFireFXBone = PRIMARY Muzzle
  WeaponMuzzleFlash = PRIMARY MuzzleFX
End
```

the hidden subobject name here is `TurretUp01`, however the subobject in the actual model is called `TURRETUP01` (the case is important)

the solution is simple, just force uppercase when `Drawable::HideSubObject` or `Drawable::ShowSubObject` is called:
```csharp
        public void HideSubObject(string subObject)
        {
            if (subObject == null) return;

            subObject = subObject.ToUpper();

            if (!_hiddenSubObjects.ContainsKey(subObject))
            {
                _hiddenSubObjects.Add(subObject, false);
            }
            _shownSubObjects.Remove(subObject);
        }
```

```csharp
        public void ShowSubObject(string subObject)
        {
            if (subObject == null) return;

            subObject = subObject.ToUpper();

            if (!_shownSubObjects.ContainsKey(subObject))
            {
                _shownSubObjects.Add(subObject, false);
            }
            _hiddenSubObjects.Remove(subObject);
        }
```
also force uppercase when checking the names in `ModelInstance::BuildRenderList`, just in case
```csharp
            for (var i = 0; i < Model.SubObjects.Length; i++)
            {
                var subObject = Model.SubObjects[i];
                var name = subObject.Name.ToUpper();
```
### second
subobjects have a special bone dedicated specifically to them. i assume that when the game requests to "hide a sub object", it means "hide a sub object and also hide its bone, hiding any child subobjects aswell"

added a little test in `ModelInstance::BuildRenderList`
```csharp
                var bone = subObject.Bone;
                var parentHidden = false;
                while (bone != null && bone.Name != null)
                {
                    if(hiddenSubObjects.ContainsKey(bone.Name))
                    {
                        parentHidden = true;
                        break;
                    }

                    bone = bone.Parent;
                }

                if(parentHidden)
                {
                    continue;
                }
```

### result

![image](https://github.com/OpenSAGE/OpenSAGE/assets/147560985/008b952a-a1ea-467a-a341-333873a2dc0e)

(ignore the radar van thing, this was captured in vanilla generals, and it doesn't have an upgrade for radar vans)

the only thing that is left is to write some decent code

**Comment by charliefoxtwo** [comment]
Another option (which might save us from making a mistake down the line) would be to make the dictionary key comparator case-insensitive? https://stackoverflow.com/a/13988953

Again, nice find!

**Comment by c001ac1d** [comment]
> make the dictionary key comparator case-insensitive

didn't even know this was possible, it looks very nice. sorry, coming from another language 😄 
i'll add that and test again

**Comment by c001ac1d** [comment]
hol up
https://github.com/OpenSAGE/OpenSAGE/blob/3636c85199381ce96e91e86a2520695f80fd788e/src/OpenSage.Game/Client/Drawable.cs#L131-L132

the dictionaries already have that comparator. i've just removed my uppercase transformations and everything still works. disregard the first point then, the case is already taken care of

**Comment by c001ac1d** [comment]
#911 fixes this
