### ISSUE TITLE
Selecting (non-additive) a single unit while having another unit selected doesn't clear the old selection

### ISSUE THREAD

**Issue by c001ac1d** [OpenSAGE/OpenSAGE#912]
note the healthbars above each unit i select. i'm not using additive selection, so the old selection should reset, but it does not
![select](https://github.com/OpenSAGE/OpenSAGE/assets/147560985/1d32b891-1c5b-4c09-80e0-6ed3c33bb0f5)

also leaving a probable solution here
https://github.com/OpenSAGE/OpenSAGE/blob/3636c85199381ce96e91e86a2520695f80fd788e/src/OpenSage.Game/Logic/Player.cs#L184-L193
we should call `DeselectUnits` in the `else` branch before assigning `_selectedUnits` to the new set

**Comment by charliefoxtwo** [comment]
Yeah I concur, seems like a simple fix!
